#!/usr/bin/env zsh
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#history in cache directory:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.cache/zsh/history

setopt AUTO_CD
unsetopt BEEP

export EDITOR=code

## ALIAS
alias vim=nvim
alias lg=lazygit
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'

##
#  Setup ASDF
#
. $(brew --prefix asdf)/libexec/asdf.sh

# Github Copilot
eval "$(github-copilot-cli alias -- "$0")"

source $HOME/antigen.zsh

antigen theme romkatv/powerlevel10k
antigen bundle zdharma-continuum/fast-syntax-highlighting

# Tell Antigen that you're done.
antigen apply

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
